SELECT RECORD_ID, ORIGINAL_BAND,SPECIES_ID,LAT_DD,LON_DD,EVENT_DATE,MIN_AGE_AT_ENC,BIRD_STATUS,HOW_OBTAINED
FROM [dbo].[AllBirdData] A
LEFT JOIN 
    (SELECT ORIGINAL_BAND, COUNT(RECORD_ID) AS SIGHTINGS
    FROM [dbo].[AllBirdData]
    WHERE SPECIES_ID IN ('1720','2040','3490','1940')
    GROUP BY ORIGINAL_BAND
    ) B
ON A.ORIGINAL_BAND = B.ORIGINAL_BAND
WHERE SIGHTINGS > 1
    --AND SPECIES_ID IN ('1720','2040','3490','1940')
    AND ISDATE(EVENT_DATE) = 1 -- EVENT_DAY<32
ORDER BY SPECIES_ID,ORIGINAL_BAND,TRY_CONVERT(DATETIME, EVENT_DATE, 101)